services:
  telegram-bot-api:
    container_name: telegram-bot-api
    image: megurobot/telegram-bot-api:latest
    restart: unless-stopped
    environment:
      USER_GID: 1000
      USER_UID: 1000
      TELEGRAM_API_ID: ${API_ID}
      TELEGRAM_API_HASH: ${API_HASH}
      TELEGRAM_STAT: true
      TELEGRAM_LOCAL: true
    env_file:
      - .env
    volumes:
      - ./container/telegram-bot-api:/var/lib/telegram-bot-api
    networks:
      telegram-bot-api:
    ports:
      - "8081:8081"
      - "8082:8082"

volumes:
  telegram-bot-api:
    name: telegram-bot-api
    external: true

networks:
  telegram-bot-api:
    name: telegram-bot-api
